-- Tạo bảng người dùng
CREATE TABLE NGUOIDUNG (
    USERNAME VARCHAR2(30) PRIMARY KEY,
    CAPBAC VARCHAR2(20),        -- Trưởng, Nhân viên, Sinh viên
    DONVI VARCHAR2(20),         -- Toán, Lý, Hóa, Hành chính
    COSO VARCHAR2(20)           -- Cơ sở 1, Cơ sở 2
);

-- Tạo bảng thông báo
CREATE TABLE THONGBAO (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOIDUNG VARCHAR2(1000),
    LABEL NUMBER                  -- Nhãn bảo mật OLS
);

-- Thêm cột LABEL$REQUIRED cho bảng THONGBAO để OLS hoạt động
-- (OLS sẽ dùng cột mặc định LABEL)
