-- Thêm người dùng mẫu u1 đến u8
INSERT INTO NGUOIDUNG VALUES ('u1', 'TRUONG', 'ALL', 'ALL');
INSERT INTO NGUOIDUNG VALUES ('u2', 'TRUONG', 'HOA', 'COSO2');
INSERT INTO NGUOIDUNG VALUES ('u3', 'TRUONG', 'LY', 'COSO2');
INSERT INTO NGUOIDUNG VALUES ('u4', 'NHANVIEN', 'HOA', 'COSO2');
INSERT INTO NGUOIDUNG VALUES ('u5', 'SINHVIEN', 'HOA', 'COSO2');
INSERT INTO NGUOIDUNG VALUES ('u6', 'TRUONG', 'HANHCHINH', 'ALL');
INSERT INTO NGUOIDUNG VALUES ('u7', 'NHANVIEN', 'ALL', 'ALL');
INSERT INTO NGUOIDUNG VALUES ('u8', 'NHANVIEN', 'HANHCHINH', 'COSO1');
COMMIT;
