BEGIN
  -- Xoá nếu tồn tại trước đó
  SA_SYSDBA.DROP_POLICY(policy_name => 'THONGBAO_POLICY');
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

-- Tạo chính sách OLS mới
BEGIN
  SA_SYSDBA.CREATE_POLICY(
    policy_name    => 'THONGBAO_POLICY',
    column_name    => 'LABEL',
    default_options => 'READ_CONTROL'
  );
END;
/

-- Tạo các component: CAPBAC, DONVI, COSO
BEGIN
  -- CAPBAC
  SA_SYSDBA.ADD_LABEL_COMPONENT('THONGBAO_POLICY', 'CAPBAC', 0, 999);
  SA_SYSDBA.ADD_LABEL('THONGBAO_POLICY', 10, 'TRUONG',   'TRUONG',   0, 'CAPBAC:10');
  SA_SYSDBA.ADD_LABEL('THONGBAO_POLICY', 20, 'NHANVIEN', 'NHANVIEN', 0, 'CAPBAC:20');
  SA_SYSDBA.ADD_LABEL('THONGBAO_POLICY', 30, 'SINHVIEN', 'SINHVIEN', 0, 'CAPBAC:30');

  -- DONVI
  SA_SYSDBA.ADD_LABEL_COMPONENT('THONGBAO_POLICY', 'DONVI', 0, 999);
  SA_SYSDBA.ADD_LABEL('THONGBAO_POLICY', 101, 'TOAN',        'TOAN',        1, 'DONVI:101');
  SA_SYSDBA.ADD_LABEL('THONGBAO_POLICY', 102, 'LY',          'LY',          1, 'DONVI:102');
  SA_SYSDBA.ADD_LABEL('THONGBAO_POLICY', 103, 'HOA',         'HOA',         1, 'DONVI:103');
  SA_SYSDBA.ADD_LABEL('THONGBAO_POLICY', 104, 'HANHCHINH',   'HANHCHINH',   1, 'DONVI:104');

  -- COSO
  SA_SYSDBA.ADD_LABEL_COMPONENT('THONGBAO_POLICY', 'COSO', 0, 999);
  SA_SYSDBA.ADD_LABEL('THONGBAO_POLICY', 201, 'COSO1', 'COSO1', 2, 'COSO:201');
  SA_SYSDBA.ADD_LABEL('THONGBAO_POLICY', 202, 'COSO2', 'COSO2', 2, 'COSO:202');
END;
/

-- Gán chính sách cho bảng
BEGIN
  SA_SYSDBA.APPLY_POLICY(
    object_schema  => 'YOUR_SCHEMA',
    object_name    => 'THONGBAO',
    policy_name    => 'THONGBAO_POLICY'
  );
END;
/
